version: '3.8'

services:
  app:
    build: ./back-end/crochemanager
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/crochemanager?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db
    volumes:
      - ./back-end/crochemanager:/app
      - ~/.m2:/root/.m2

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crochemanager
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./front-end:/usr/share/nginx/html
    depends_on:
      - app

volumes:
  db_data:
